# Generated by Django 4.1.1 on 2022-09-16 15:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(
                default=api.models.get_room_code, max_length=10, unique=True
            ),
        ),
    ]
